### PR TITLE
20230905 improve errors ber sizing

### LINKED ISSUE #28: Add support for unsupported controls
We've run into an issue with a client sending extra controls with their request, that we don't care about but fail the query parsing: https://github.com/lldap/lldap/issues/301
The error is `Unsupported control oid | o: 2.16.840.1.113730.3.4.2`, and then `Failed to parse ldapcontrol`

Would there be a way to either add support for the controls, or add a "parse with unsupported controls as an extra return" method?

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #28 - this is a large clean up that improves error handling, better support for controls, resolves a lot of clippy lints, and add's max-ber-size limiting to the ldapcodec.

### CODE REVIEW

File: cli/src/ldap.rs [hunk 1]
```diff
@@ -43,21 +43,19 @@ async fn main() {
...
+                "{}",
+                serde_json::to_string_pretty(&e).expect("CRITICAL: Serialisation Fault")
+            );
         } else {
-            ("".to_string(), "".to_string())
+            error!("Anonymous does not take a password - {}", e);
         }
+        std::process::exit(e as i32);
+    } else {
+        ("".to_string(), "".to_string())
```
Comment (nitnelave) [inline cli/src/ldap.rs:58]: `String::new()`?

File: proto/src/error.rs [hunk 2]
```diff
@@ -0,0 +1,131 @@
+use thiserror::Error;
+
+#[derive(Error, Debug)]
+pub enum LdapProtoError {
```
Comment (nitnelave) [inline proto/src/error.rs:4]: Listing all potential errors seems a bit brittle, maybe?

What about some categories, like "invalid BER" with a string for the details? Or are you specifically trying to avoid String/allocations?
At the very least I would make this enum non-exhaustive, so adding a new error is not a breaking change.

File: proto/src/lib.rs [hunk 3]
```diff
@@ -31,10 +32,29 @@ use tokio_util::codec::{Decoder, Encoder};
 use tracing::{error, trace};
 
 pub use crate::filter::parse_ldap_filter_str;
-use crate::proto::LdapMsg;
 pub use crate::simple::*;
 
-pub struct LdapCodec;
+const KILOBYTES: usize = 1048576;
```
Comment (nitnelave) [inline proto/src/lib.rs:37]: Megabytes? :D

File: proto/src/lib.rs [hunk 4]
```diff
@@ -59,8 +79,14 @@ impl Decoder for LdapCodec {
...
         let size = buf.len() - rem.len();
 
+        if size > self.max_ber_size {
+            return Err(io::Error::new(
+                io::ErrorKind::OutOfMemory,
+                "lber request too large",
+            ));
+        }
+
         // helper for when we need to debug inputs.
```
Comment (nitnelave) [inline proto/src/lib.rs:89]: Remove the comment

File: proto/src/lib.rs [hunk 5]
```diff
@@ -96,7 +122,7 @@ mod tests {
         ($req:expr) => {{
             let _ = tracing_subscriber::fmt::try_init();
```
Comment (nitnelave) [inline proto/src/lib.rs:123]: Unwrap, since we're in tests?

**Review by nitnelave — APPROVED** [review]

File: proto/src/error.rs (hunk 2 above)
Comment (nitnelave) [reply proto/src/error.rs:4]: Also, do we use this anywhere?

File: proto/src/lib.rs (hunk 5 above)
Comment (Firstyear) [reply proto/src/lib.rs:123]: If you unwrap half the tests fail because tracing sub fails to setup. What happens is tracing sub "races" in all the tests and only one succeeds, and the rest error. 

So actually, we do need the let _ for all the ones that fail... it's a bit of a silly design on part of tracing.

File: proto/src/error.rs (hunk 2 above)
Comment (Firstyear) [reply proto/src/error.rs:4]: Yeah, I'm avoiding string allocs here. The idea is each error encodes "what and where" it occured. It's kind of a "learnt lesson" from kanidm where we used generic errors, people would say "we had X error" and then there are a few hundreds places it could arise from. So we are moving to more precise errors in Kanidm, and an example would be in kani to wrap this as:

`LdapE001 ( LdapProtoError )`

Which then tells us precisely where the error was, and in this case, also extends to tell us more about what Ldap error occured too. This also then has implications for internationalisation because then we can have translations later since we avoided human strings. It also saves space in serialisation/encoding since we could choose to repr this as u16 or similar instead of strings in Json. So generally this is "forward looking" to a large error rework with Kanidm.

**Comment by Firstyear** [comment]
@nitnelave Updated with improved debug display of fields.

File: proto/src/error.rs (hunk 2 above)
Comment (nitnelave) [reply proto/src/error.rs:4]: You don't want to at least make the enum non exhaustive?

**Comment by nitnelave** [comment]
Sorry for some reason I couldn't comment on the line (I blame the mobile interface). In the bytes_to_string, it would make sense to know when something is base 64 or not. Maybe

```
field: "raw_string"
field: base64[abcde123]
```

WDYT ?

**Comment by Firstyear** [comment]
I think you're right, it helps to distinguish the two cases (a string that has base64 chars, vs binary that was b64ed for debug).

**Review by nitnelave — APPROVED** [review]
